# Generated by Django 2.1.4 on 2019-01-13 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.IntegerField(default=1)),
                ('game_mode', models.IntegerField(default=0)),
                ('player_number', models.IntegerField(default=0)),
                ('full', models.BooleanField(default=False)),
                ('started', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerOnGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shake_times', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tow.GameInfo')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('pwd', models.CharField(max_length=32)),
                ('on_game', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='playerongame',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tow.UserInfo'),
        ),
    ]
