# Generated by Django 2.1.4 on 2019-01-13 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tow', '0002_auto_20190113_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='username',
            field=models.CharField(default='nameless', max_length=128, unique=True),
        ),
    ]
