# Generated by Django 2.1.4 on 2019-01-13 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tow', '0003_auto_20190113_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerongame',
            name='percent',
            field=models.IntegerField(default=0),
        ),
    ]
