# Generated by Django 2.1.4 on 2019-01-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tow', '0004_playerongame_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerongame',
            name='shake_times',
            field=models.FloatField(default=0),
        ),
    ]
