# Generated by Django 2.1.4 on 2019-01-16 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tow', '0006_gameinfo_max_game_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinfo',
            name='game_mode',
            field=models.IntegerField(default=1, unique=True),
        ),
    ]
