# Generated by Django 2.1.4 on 2019-01-16 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tow', '0007_auto_20190116_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerongame',
            name='percent',
        ),
    ]
