# Generated by Django 2.1.4 on 2019-01-16 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tow', '0008_remove_playerongame_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerongame',
            name='ready',
            field=models.BooleanField(default=False),
        ),
    ]
