# Generated by Django 2.1.4 on 2019-01-17 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tow', '0009_playerongame_ready'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerongame',
            name='on_wait',
            field=models.BooleanField(default=False),
        ),
    ]
